# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "tgm-hit-protocol"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = [
  "Simon Gao <https://github.com/k1W1M4ng0>"
]
license = "MIT"
description = "Protocol template for students of the HIT department at TGM Wien"
# homepage = ""
repository = "https://github.com/k1W1M4ng0/typst-protocol"
keywords = ["TGM", "HIT", "protocol", "HTL", "SYT"]
categories = ["report"]
disciplines = ["computer-science"]
compiler = ""
exclude = [
	".github",
	"docs",
	"gallery",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
