[conf]
default-lang = "en"

[lang.en]
supervisor = "Supervisor"

chapter = "Chapter"
section = "Section"
abstract = "Abstract"

figure = "Figure"
table = "Table"
listing = "Listing"

contents = "Contents"
bibliography = "Bibliography"
list-of-figures = "List of Figures"
list-of-tables = "List of Tables"
list-of-listings = "List of Listings"
glossary = "Glossary"

[lang.de]
supervisor = "Betreuer"

chapter = "Kapitel"
section = "Abschnitt"
abstract = "Kurzfassung"

figure = "Abbildung"
table = "Tabelle"
listing = "Auflistung"

contents = "Inhaltsverzeichnis"
bibliography = "Literaturverzeichnis"
list-of-figures = "Abbildungsverzeichnis"
list-of-tables = "Tabellenverzeichnis"
list-of-listings = "Auflistungsverzeichnis"
glossary = "Glossar"
